// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFNAxRwisuzE_lQhvKzXONBhxFLEVmCRM',
    appId: '1:107010768252:android:e88d55fe486eb120f538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    storageBucket: 'sistem-academic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmhgKgqafEZLsw0rB6SOAqX3yD9cyudSg',
    appId: '1:107010768252:ios:83ea4b2c5242b457f538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    storageBucket: 'sistem-academic.firebasestorage.app',
    androidClientId: '107010768252-dg7b3o6dn2b0ha9pjrl5c71pj8opcgfv.apps.googleusercontent.com',
    iosClientId: '107010768252-kk4etc0hmkvbguus1bs210r29k6u4fst.apps.googleusercontent.com',
    iosBundleId: 'com.example.spkMobile',
  );
}
